# Defines the schema for the theme settings configuration.
# This ensures that all color settings are correctly saved to the database.
kingly_minimal.settings:
  type: theme_settings
  label: 'Kingly Minimal settings'
  mapping:
    # --------------------------------------------------------------------------
    # Global Colors (from _variables.scss)
    # --------------------------------------------------------------------------
    color_text:
      type: string
      label: 'Text Color'
    color_background:
      type: string
      label: 'Background Color'
    color_primary:
      type: string
      label: 'Primary Color'
    color_primary_hover:
      type: string
      label: 'Primary Hover Color'
    color_border:
      type: string
      label: 'Border Color'
    color_light_gray:
      type: string
      label: 'Light Gray Color'
    color_rating:
      type: string
      label: 'Rating Color'
    focus_ring_color:
      type: string
      label: 'Focus Ring Color'
    color_status:
      type: string
      label: 'Status Background Color'
    color_status_text:
      type: string
      label: 'Status Text Color'
    color_status_border:
      type: string
      label: 'Status Border Color'
    color_warning:
      type: string
      label: 'Warning Background Color'
    color_warning_text:
      type: string
      label: 'Warning Text Color'
    color_warning_border:
      type: string
      label: 'Warning Border Color'
    color_error:
      type: string
      label: 'Error Background Color'
    color_error_text:
      type: string
      label: 'Error Text Color'
    color_error_border:
      type: string
      label: 'Error Border Color'
    # Dark Mode
    dark_color_text:
      type: string
      label: 'Dark: Text Color'
    dark_color_background:
      type: string
      label: 'Dark: Background Color'
    dark_color_primary:
      type: string
      label: 'Dark: Primary Color'
    dark_color_primary_hover:
      type: string
      label: 'Dark: Primary Hover Color'
    dark_color_border:
      type: string
      label: 'Dark: Border Color'
    dark_color_light_gray:
      type: string
      label: 'Dark: Light Gray Color'
    dark_color_rating:
      type: string
      label: 'Dark: Rating Color'
    dark_focus_ring_color:
      type: string
      label: 'Dark: Focus Ring Color'
    dark_color_status:
      type: string
      label: 'Dark: Status Background Color'
    dark_color_status_text:
      type: string
      label: 'Dark: Status Text Color'
    dark_color_status_border:
      type: string
      label: 'Dark: Status Border Color'
    dark_color_warning:
      type: string
      label: 'Dark: Warning Background Color'
    dark_color_warning_text:
      type: string
      label: 'Dark: Warning Text Color'
    dark_color_warning_border:
      type: string
      label: 'Dark: Warning Border Color'
    dark_color_error:
      type: string
      label: 'Dark: Error Background Color'
    dark_color_error_text:
      type: string
      label: 'Dark: Error Text Color'
    dark_color_error_border:
      type: string
      label: 'Dark: Error Border Color'

    # --------------------------------------------------------------------------
    # Layout Colors
    # --------------------------------------------------------------------------
    # Footer
    footer_background_color:
      type: string
      label: 'Footer Background Color'
    footer_text_color:
      type: string
      label: 'Footer Text Color'
    footer_border_color:
      type: string
      label: 'Footer Border Color'
    dark_footer_background_color:
      type: string
      label: 'Dark: Footer Background Color'
    dark_footer_text_color:
      type: string
      label: 'Dark: Footer Text Color'
    dark_footer_border_color:
      type: string
      label: 'Dark: Footer Border Color'
